_target_: packages.vq.src.vq.modeling_vq.RVQVAE_Smpl

input_width:        337
nb_code:            512
code_dim:           512
output_emb_width:   512
down_t:             2
stride_t:           2
width:              512
depth:              3
dilation_growth_rate: 3
activation:         relu
norm:               null

num_quantizers:         6
shared_codebook:        false
quantize_dropout_prob:  0.2
