defaults:
  - _self_         
  - override hydra/job_logging: disabled

# paths -------------------------------------------------
#ckpt_path: /data/guichoux/MATCHALINA/checkpoints/beat/beat_mls-pt_ltts_mls_ggsp-167M-1qz-lr5e-5/checkpoint_epoch=3_step=3976_val_loss_avg=3.9097.ckpt
ckpt_path: '/data/guichoux/MATCHALINA/checkpoints/beat/checkpoint_epoch=2_step=2571_val_loss_avg=3.9271-local.ckpt'
wavtok_cfg: checkpoints/wavtokenizer/wavtokenizer_mediumdata_frame75_3s_nq1_code4096_dim512_kmeans200_attn.yaml
wavtok_ckpt: checkpoints/wavtokenizer/wavtokenizer_medium_speech_320_24k.ckpt
motion_vq_ckpt: checkpoints/vq_beat_V3-body_only/vq_beat_V3-body_only-epoch=06-val_loss_rec=0.03.ckpt
global_vq_cfg: configs/others/global_vq.yml
output_dir: out/default/
prompt_path: null

# synthesis knobs --------------------------------------
max_seqlen: 2500
k_speech: 100
k_motion: 20
temp_speech: [1.0]
temp_motion: [0.8]
first_greedy_quant_speech: 1
first_greedy_quant_motion: 1
mask_motion_tokens: false
batch_size: 8
residuals: 1

zero_trans: false
zero_hands: true

device: cuda:0
#text: "Right, so we have got this duck here, and we are gonna throw it in the water to see if it floats, because, obviously, if it does, that means she is made of wood, and therefore she must be a witch! It is completely logical, dont question it, because if the duck floats, we will tie her to a chair, set her on fire, and be done with it." # No one can argue with this flawless reasoning!"
text: "According to the manifold hypothesis, most natural data lies on manifolds with significantly reduced intrinsic dimensionality. Consequently, identifying these manifolds and training diffusion models directly on them can be advantageous due to the lower data dimensionality filler filler filler."
text: "I have walked into the palaces of kings and queens and into the houses of presidents. And much more. But I could not walk into a hotel in America and get a cup of coffee, and that made me mad. Filler Filler."
text: "Surely the day will come when color means nothing more than the skin tone, when religion is seen uniquely as a way to speak one's soul, when birth places have the weight of a throw of the dice and all men are born free, when understanding breeds love and brotherhood. Filler Filler."