defaults:
  - _self_         
  - override hydra/job_logging: disabled

gt_folder: out/infer_dataset/gt
gen_folder: out/infer_dataset/cloning_2025-07-21_15-21-47

root_dir: /data/guichoux/

evaluated_speakers: [2] #'all' #[ 1  2  3  4  5  6  7  9 10 11 12 13 15 16 17 18 20 21 22 23 24 25 27 28 30]

